export const ACTION_ERROR = 'ACTION_ERROR';

export const GET_CORGIS_FOR_SALE_START = 'ACTION_START';
export const GET_CORGIS_FOR_SALE_SUCCESS = 'GET_GLOBAL_CORGIS_SUCCESS';

export const ADD_CORGI_FOR_SALE_START = 'ADD_CORGI_FOR_SALE_START';
export const ADD_CORGI_FOR_SALE_SUCCESS = 'ADD_CORGI_FOR_SALE_SUCCESS';

export const BID_FOR_CORGI_START = 'BID_FOR_CORGI_START';
export const BID_FOR_CORGI_SUCCESS = 'BID_FOR_CORGI_SUCCESS';

export const CLEARANCE_FOR_CORGI_START = 'CLEARANCE_FOR_CORGI_START';
export const CLEARANCE_FOR_CORGI_SUCCESS = 'CLEARANCE_FOR_CORGI_SUCCESS';

export const CLEAR_STATE = 'CLEAR_STATE';
