export const FOUND_RECEIVER_SUCCESS = 'FOUND_RECEIVER_SUCCESS';
export const FOUND_RECEIVER_ERROR = 'FOUND_RECEIVER_ERROR';
export const SET_RECEIVER = 'SET_RECEIVER';
export const SET_MESSAGE = 'SET_MESSAGE';
