export const ACTION_START = 'ACTION_START';
export const ACTION_ERROR = 'ACTION_ERROR';

export const GET_CORGI_SUCCESS = 'GET_CORGI_SUCCESS';

export const GET_CORGIS_SUCCESS = 'GET_CORGIS_SUCCESS';

export const GET_GLOBAL_CORGIS_SUCCESS = 'GET_GLOBAL_CORGIS_SUCCESS';

export const CREATE_CORGI_START = 'CREATE_CORGI_START';
export const CREATE_CORGI_SUCCESS = 'CREATE_CORGI_SUCCESS';

export const DELETE_CORGI_START = 'DELETE_CORGI_START';
export const DELETE_CORGI_SUCCESS = 'DELETE_CORGI_SUCCESS';

export const TRANSFER_CORGI_START = 'TRANSFER_CORGI_START';
export const TRANSFER_CORGI_SUCCESS = 'TRANSFER_CORGI_SUCCESS';

export const CLEAR_STATE = 'CLEAR_STATE';
